exhaust_test: false


# ModelParams
scene_type: "DriveXWaymo"
resolution_scales: [1, 2, 4, 8, 16]
cam_num: 3
eval: true
num_pts: 600000
t_init: 0.025 

start_time: 1
end_time: 198

 
order: 8 
bbox_frame_interval: 3 

load_sky_mask: true
load_dynamic_mask: true
load_bbox_mask: true

# PipelineParams

# OptimizationParams
iterations: 120000 

opacity_lr: 0.005

densify_until_iter: 30000 
densify_grad_threshold: 0.00017
sh_increase_interval: 2000


prune_interval: 200

render_type: DeformableGS

static_thresh: 1.0

thresh_opa_prune: 0.005
opa_init: 0.01
